/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppSettingSchema extends BaseModel {
  static $columns = ['accentColor', 'backgroundColor', 'createdAt', 'id', 'updatedAt'] as const
  $columns = AppSettingSchema.$columns
  @column()
  declare accentColor: string | null
  @column()
  declare backgroundColor: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WeatherLocationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'latitude', 'longitude', 'name', 'updatedAt'] as const
  $columns = WeatherLocationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SlideSchema extends BaseModel {
  static $columns = [
    'id',
    'content',
    'media',
    'mediaType',
    'mediaName',
    'createdAt',
    'updatedAt',
  ] as const

  $columns = SlideSchema.$columns

  @column({ isPrimary: true })
  declare id: number

  @column()
  declare content: string

  @column()
  declare media: string | null

  @column()
  declare mediaType: string | null

  @column()
  declare mediaName: string | null

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
