/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppSettingSchema extends BaseModel {
  static $columns = ['accentColor', 'backgroundColor', 'createdAt', 'id', 'tenantId', 'textColor', 'updatedAt'] as const
  $columns = AppSettingSchema.$columns
  @column()
  declare accentColor: string | null
  @column()
  declare backgroundColor: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tenantId: number | null
  @column()
  declare textColor: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SlideSchema extends BaseModel {
  static $columns = ['content', 'contentColor', 'createdAt', 'duration', 'id', 'isActive', 'media', 'mediaName', 'mediaType', 'order', 'tenantId', 'title', 'titleColor', 'updatedAt'] as const
  $columns = SlideSchema.$columns
  @column()
  declare content: string
  @column()
  declare contentColor: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare duration: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare media: string | null
  @column()
  declare mediaName: string | null
  @column()
  declare mediaType: string | null
  @column()
  declare order: number
  @column()
  declare tenantId: number | null
  @column()
  declare title: string
  @column()
  declare titleColor: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = TenantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'tenantId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare tenantId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WeatherLocationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'latitude', 'longitude', 'name', 'tenantId', 'updatedAt'] as const
  $columns = WeatherLocationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare name: string
  @column()
  declare tenantId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
